### ISSUE TITLE
Proper mime type for bundles

### ISSUE THREAD

**Issue by stikkireddy** [renardeinside/schorle#7]
* https://github.com/renardeinside/schorle/blob/93801fd2233df2c5102d41b1398e6d565065d716/src/python/schorle/app.py#L31-L36
When responding back with bundle.js or other assets, maybe guess the mime type:

```python
import mimetypes
print(mimetypes.MimeTypes().guess_type('my_file.txt')[0])
```

When proxy is configured to add headers `X-Content-Type-Options` set to `nosniff`, browsers enforce mime types preventing the bundle.js from being executed which prevents the proper csrf token being sent to the websocket connection and this breaks the whole interactivity of the app.

**Comment by renardeinside** [comment]
fixed in relevant PR, will release as soon as I fix the TS building logic for releases. 

Thanks a lot for pointing out this one! 🙌
